### ISSUE TITLE
Wraith Spawn egg

### ISSUE THREAD

**Issue by NicosaurusRex99** [TheSlayerMC/Journey-1.12#1]
Alexandru came to me in my discord and came forth with a random crash. i found the source and here is my suggestion

`public static void registerMob(Class entityClass, String name, String finalN, int base, int fore) {
		LangRegistry.addMob(name, finalN);
		EntityRegistry.registerModEntity(new ResourceLocation(MOD_ID, name), entityClass, name, mobID++, JITL.instance, 128, 5, true, base, fore);
	}`
causes the Wraith to crash based on a stat dupe.
make the wraith a seperate registerMobNoEgg maybe? 
`public static void registerMobNoEgg(Class entityClass, String name, String finalN) {
		LangRegistry.addMob(name, finalN);
		EntityRegistry.registerModEntity(new ResourceLocation(MOD_ID, name), entityClass, name, mobID++, JITL.instance, 128, 5, true);
	}`

Log https://pastebin.com/2XdBiWdG

**Comment by NicosaurusRex99** [comment]
Again, https://pastebin.com/cpFK8ute
It is the wraith spawn egg causing this issue

**Comment by Dizzlepop12** [comment]
We'll look into it
