### ISSUE TITLE
2 portal issues

### ISSUE THREAD

**Issue by Zack7292** [TheSlayerMC/Journey-1.12#16]
1.: weird portal gen, i think its cause by the x/y axes.
![image](https://user-images.githubusercontent.com/45187146/75606639-cf825c80-5abc-11ea-9ec2-eb3be75c564a.png)
this happened with pretty much all the portals

2. a tree spawn in my portal, i think its kinda dumb, but still should be fix to make it cleaner
![image](https://user-images.githubusercontent.com/45187146/75606656-f9d41a00-5abc-11ea-88c6-c87400ef5391.png)

**Comment by AllShamNoWow101** [comment]
All fixed
