### ISSUE TITLE
Is there an official download link for 1.12.x?

### ISSUE THREAD

**Issue by Derpitron** [TheSlayerMC/Journey-1.12#2]
I would love to ~~torture my computer~~ run a modpack using this, and even mundane things such as Sky Eels spawning in a dimension from AoA similar to that of Cloudia makes me all hyped, but I can't find any download link, please help me find it!

Sincerely, A Mod Enthusiast

**Comment by AllShamNoWow101** [comment]
https://ouo.io/VPUub3
