### ISSUE TITLE
Depts Slayer-strange damage

### ISSUE THREAD

**Issue by HioshiTsuki** [TheSlayerMC/Journey-1.12#33]
Is it normal that Depths Slayer kills all mobs from JITL mod in one hit?
I tried to kill Eudor,Temple Guardian,Corallator,Soul Watcher and mobs,but they were killed in one hit
But it didn`t work with Wither boss and moreover skeletons couldn`t be killed with this sword

**Comment by AllShamNoWow101** [comment]
Problem fixed in next release
