### ISSUE TITLE
random crash with Various Oddities

### ISSUE THREAD

**Issue by Zack7292** [TheSlayerMC/Journey-1.12#45]
i've was exploring caves and i got this crash, don't really understand how tho

Crash log:https://pastebin.com/FL4MzMLL

Various oddities: https://www.curseforge.com/minecraft/mc-mods/various-oddities

bug report on the Various oddities page (may help?): https://www.curseforge.com/minecraft/mc-mods/various-oddities/issues/81

**Comment by AllShamNoWow101** [comment]
From what i can see its from their end, something in their entity file pointing to null (nothing) causing a crash

**Comment by Zack7292** [comment]
ok thx :)
