### ISSUE TITLE
Bug in mod Journey Into The Light

### ISSUE THREAD

**Issue by RustinShow** [TheSlayerMC/Journey-1.12#47]
The enchantment of the hot touch and water walking not working.
Hot Touch it only produces ore but does not produce blocks.
Mod version - Journey-1.12.2-1.0.5.16b
Fix please.
https://youtu.be/HM4R3wZukG8

**Comment by AllShamNoWow101** [comment]
Hot touch is only used to drop things that are smeltable, hense why ores and wood ect work but is designed to not drop anything else

Water walker may be removed yet as frost walker exists in the game now
