### ISSUE TITLE
[1.12.2] Game crash when right clicking fully grown vanilla seeds

### ISSUE THREAD

**Issue by aking4125** [TheSlayerMC/Journey-1.12#67]
Hello!

We are getting this crash each time a fully grown vanilla crop is right-clicked. Simple harvest was removed. Any ideas? Crash log points to JITL and Baubles. Only occurs with vanilla crops.

[crash-2021-09-03_17.10.20-client.txt](https://github.com/TheSlayerMC/Journey-Into-The-Light/files/7108757/crash-2021-09-03_17.10.20-client.txt)

**Comment by TimeConqueror** [comment]
Thanks for the issue! Fixed in 1.0.6.10!

**Comment by aking4125** [comment]
Sadly, this isn't fixed with the latest version. Again, when right-clicking a fully grown vanilla crop, the game crashes. 

This time the crash is different. But still points to JITL. 

[crash-2021-09-04_08.25.27-client.txt](https://github.com/TheSlayerMC/Journey-Into-The-Light/files/7109742/crash-2021-09-04_08.25.27-client.txt)

**Comment by TimeConqueror** [comment]
Yep, that was another issue, now fixed too (1.0.6.11), thanks!

**Comment by aking4125** [comment]
Thanks! Can confirm this fixed the problem!
